### ISSUE TITLE
Twilio Driver uses TwiML API, meaning it can never originate a conversation.

### ISSUE THREAD

**Issue by DanielCoulbourne** [botman/driver-twilio#4]
Twilio's TwiML API format is 100% based on the client (botman) issuing responses on a webhook URL. This means that we can never initiate a conversation.

**Comment by mpociot** [comment]
Hm right. We would need to use this POST endpoint: https://www.twilio.com/docs/api/messaging/send-messages
It requires the AccountSid , which the driver currently does not use. 

I can add this and tag a 2.0 👍

**Comment by DanielCoulbourne** [comment]
Check out the diff on this branch. It's still broken (for somereason $message->getSender() is null) but it's close
https://github.com/DanielCoulbourne/driver-twilio/tree/dev-twilio-initiate-bugfix

**Comment by jstowell29** [comment]
Would love to see this added in order to initiate a conversation...

**Comment by mpociot** [comment]
I updated the Twilio driver to have support for this 👍 
https://github.com/botman/driver-twilio/commit/c6accd7198b269c9b8e53c5a31ce97e20d28a11a
